package Testng;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.SkipException;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

import Selenium.Practice.com.Nisum.Reusableclass;
import junit.framework.Assert;
import org.testng.annotations.Test;

@Listeners(Testng.Listeners_types.class)
public class Listeners_class {
	
/*	ITestListener
	onStart--onFinish--onTestStart--onTestSkipped--onTestSuccess--onTestFailure

	For every ITestListener method we usually pass the following arguments:

	1)“ITestResult” interface along with its instance, “result,” which describes the result of a test. Note: If you want to trace your exception through ITestResult then you need to avoid try/catch handling.
	2)“ITestContext” interface along with its instance “context” which describes the test context containing all the information of the given test run.

	IReporter = TestNG listener in Selenium WebDriver provides an interface which helps you to customize the test report generated by TestNG. It provides the generateReport method which gets invoked after the execution of all the suites.

	 IRetryAnalyzer interface  = failed test cases will run 3 times till it passes. In case it fails the third time, test execution will stop and TestNG will mark this case as failed.
	*/
	WebDriver d;

	//public class TestNGListenersTest {
	    @Test //Passing Test 
	    public void sampleTest1() throws InterruptedException { 
			System.setProperty("webdriver.gecko.driver",Reusableclass.setPath("/src/drivers/geckodriver.exe"));
			d = new FirefoxDriver();
			d.manage().window().maximize();
			//driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);

			d.get("https://www.amazon.in");
			Thread.sleep(3000);
			d.findElement(By.id("a-autoid-0-announce")).click();

			WebDriverWait wait = new WebDriverWait(d,30);
			wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("ap_email")));

			WebDriverWait waitforbutton = new WebDriverWait(d,30);
			waitforbutton.until(ExpectedConditions.elementToBeClickable(By.id("continue")));
			waitforbutton.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[contains(text(),'  Enter your email or mobile phone number')]")));
			waitforbutton.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//span[contains(text(),'Need help?')]")));
	d.close();
	}
	@Test //Failing Test 
	public void sampleTest2() throws InterruptedException { 
	System.out.println("Forcely Failed Test Method");
	Assert.assertTrue(false);
	}
	private int i = 0;
	@Test(successPercentage = 60, invocationCount = 5) //Test Failing But Within Success Percentage 
	public void sampleTest3() { i++; 
	System.out.println("Test Failed But Within Success Percentage Test Method, invocation count: " + i); 
	if (i == 1 || i == 2) { 
		System.out.println("sampleTest3 Failed"); 
		Assert.assertEquals(i, 6); } } 
}
